version: '3'
services:
  db:
    container_name: ecrpe_db_test
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    security_opt:
      - seccomp:unconfined
    ports:
      - 7359:3306
    volumes:
      - /Users/rd/Coding/go/src/github.com/juleur/becrpe/sql/:/var/local
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecrpe
      MYSQL_USER: chermak
      MYSQL_PASSWORD: pwd
  cache:
    container_name: ecrpe_redis_test
    image: redis
    restart: always
    ports:
      - 8989:6379